### ISSUE TITLE
East-West Routing and Scalability | Feature Request

### ISSUE THREAD

**Issue by seeravinder** [aws-samples/traffic-inspection-architectures-aws-cloud-wan#1]
The East-West traffic needs a static route for every VPC, in a large network it is not possible to add one static route per VPC, it must be dynamic. Static aggregates are okay though.
Can we request to have the functionality of Share filter per region?

**Comment by pablo19sc** [comment]
Hi!

Sorry for the delay on this, I missed this somehow. This repo tries to show a way to simplify the creation of these static routes using Terraform - for CloudFormation we are working on that.

As soon as Cloud WAN enables to have a simpler way to add the inspection layer, I'll update this repo. Ask your AWS Account Team to add that Feature Request to our Cloud WAN team.
