### ISSUE TITLE
Not able to retreive AMI

### ISSUE THREAD

**Issue by pmankad96** [aws-samples/traffic-inspection-architectures-aws-cloud-wan#2]
When using the compute module data code, not able retrieve the AMI. I was able to retrieve it using SSM, here is code sample:

```
# Data resource to determine the latest Amazon Linux2 AMI
data "aws_ssm_parameter" "my-amzn-linux-ami" {
  name     = "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
}
```

**Comment by pablo19sc** [comment]
Fixed in https://github.com/aws-samples/traffic-inspection-architectures-aws-cloud-wan/pull/3. Closing issues
